name       : wine
version    : 1.8.1
release    : 7
source     :
    - https://dl.winehq.org/wine/source/1.8/wine-1.8.1.tar.bz2 : 149ad3daaf8593b36c5c061285df0ec2a25e20ea48c61323be91088c4d22ca97
license    : LGPL-2.1
component  : virt
summary    : Wine compatibility layer for Windows emulation.
description: |
    Wine (originally an acronym for "Wine Is Not an Emulator") is a compatibility layer capable of running Windows applications on several POSIX-compliant operating systems, such as Linux, Mac OSX, & BSD. Instead of simulating internal Windows logic like a virtual machine or emulator, Wine translates Windows API calls into POSIX calls on-the-fly, eliminating the performance and memory penalties of other methods and allowing you to cleanly integrate Windows applications into your desktop.
builddeps  :
    - pkgconfig32(dbus-1)
    - pkgconfig32(fontconfig)
    - pkgconfig32(freetype2)
    - pkgconfig32(glu)
    - pkgconfig32(gnutls)
    - pkgconfig32(ice)
    - pkgconfig32(lcms2)
    - pkgconfig32(libgphoto2)
    - pkgconfig32(libmpg123)
    - pkgconfig32(libpng)
    - pkgconfig32(libtiff-4)
    - pkgconfig32(libpulse)
    - pkgconfig32(libv4l1)
    - pkgconfig32(libxslt)
    - pkgconfig32(ocl-icd)
    - pkgconfig32(openal)
    - pkgconfig32(x11)
    - pkgconfig32(xcursor)
    - pkgconfig32(xi)
    - pkgconfig32(xinerama)
    - pkgconfig32(xrandr)
    - pkgconfig32(xshmfence)
    - pkgconfig32(xxf86vm)
    - pkgconfig32(zlib)
    - cups-32bit-devel
    - glibc-32bit-devel
    - libgcc-32bit
    - libjpeg-turbo-32bit-devel
    - libpth-32bit-devel
    - ncurses-32bit-devel
    - openldap-32bit-devel
    - unixodbc-32bit-devel
rundeps    :
    - freetype2-32bit
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
