name       : wine
version    : 1.8.1
release    : 3
source     :
    - https://dl.winehq.org/wine/source/1.8/wine-1.8.1.tar.bz2 : 149ad3daaf8593b36c5c061285df0ec2a25e20ea48c61323be91088c4d22ca97
license    : LGPL-2.1
summary    : Wine compatibility layer for Windows emulation.
description: |
    Wine (originally an acronym for "Wine Is Not an Emulator") is a compatibility layer capable of running Windows applications on several POSIX-compliant operating systems, such as Linux, Mac OSX, & BSD. Instead of simulating internal Windows logic like a virtual machine or emulator, Wine translates Windows API calls into POSIX calls on-the-fly, eliminating the performance and memory penalties of other methods and allowing you to cleanly integrate Windows applications into your desktop.
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
    - libjpeg-turbo-32bit-devel
    - pkgconfig32(fontconfig)
    - pkgconfig32(freetype2)
    - pkgconfig32(glu)
    - pkgconfig32(libpng)
    - pkgconfig32(libtiff-4)
    - pkgconfig32(x11)
    - pkgconfig32(xcursor)
    - pkgconfig32(xrandr)
    - pkgconfig32(xshmfence)
    - pkgconfig32(xxf86vm)
    # Need to rebuild pulse with 32bit
    #- pkgconfig32(libpulse)
rundeps    :
    - freetype2-32bit
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
